# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonstate',
            name='variable_map',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='given_code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='sourcestate',
            name='hint',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='state',
            name='tree',
            field=models.TextField(default=''),
        ),
    ]
