# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0002_auto_20170113_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonstate',
            name='variable_map',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='problem',
            name='given_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sourcestate',
            name='hint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='tree',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='condition',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
