# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0003_auto_20170113_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='course_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='hintgen.Course'),
        ),
    ]
