# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0004_auto_20170113_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='courses',
            field=models.ManyToManyField(related_name='problems', to='hintgen.Course'),
        ),
        migrations.AlterField(
            model_name='state',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hintgen.Problem'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hintgen.Course'),
        ),
        migrations.AlterField(
            model_name='test',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='hintgen.Problem'),
        ),
    ]
