# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0005_auto_20170113_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='problem_id',
            new_name='problem',
        ),
    ]
