# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0007_auto_20170114_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcestate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_states', to='hintgen.Student'),
        ),
    ]
