# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0010_auto_20170114_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcestate',
            name='hint_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='treeWeight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
