# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0011_auto_20170114_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonstate',
            name='canonical_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anon_states', to='hintgen.CanonicalState'),
        ),
        migrations.AlterField(
            model_name='anonstate',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anon_feeder', to='hintgen.State'),
        ),
        migrations.AlterField(
            model_name='anonstate',
            name='nextstep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anon_prev', to='hintgen.State'),
        ),
        migrations.AlterField(
            model_name='canonicalstate',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_feeder', to='hintgen.State'),
        ),
        migrations.AlterField(
            model_name='canonicalstate',
            name='nextstep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canonical_prev', to='hintgen.State'),
        ),
        migrations.AlterField(
            model_name='cleanedstate',
            name='anon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaned_states', to='hintgen.AnonState'),
        ),
        migrations.AlterField(
            model_name='sourcestate',
            name='cleaned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_states', to='hintgen.CleanedState'),
        ),
    ]
