# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-14 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0012_auto_20170114_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='arguments',
            field=models.CharField(max_length=500),
        ),
    ]
