# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0015_auto_20170114_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='teacher_solution',
            new_name='solution',
        ),
    ]
