# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0016_auto_20170114_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='tree',
            new_name='tree_source',
        ),
    ]
