# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0017_auto_20170114_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_extra',
            field=models.TextField(blank=True),
        ),
    ]
