# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0018_test_test_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalstate',
            name='orig_tree_source',
            field=models.TextField(blank=True),
        ),
    ]
