# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0019_canonicalstate_orig_tree_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='anonstate',
            old_name='nextstep',
            new_name='next',
        ),
        migrations.RenameField(
            model_name='canonicalstate',
            old_name='nextstep',
            new_name='next',
        ),
        migrations.RemoveField(
            model_name='anonstate',
            name='variable_map',
        ),
        migrations.RemoveField(
            model_name='sourcestate',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='sourcestate',
            name='hint_level',
        ),
        migrations.AddField(
            model_name='anonstate',
            name='orig_tree_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sourcestate',
            name='hintmsg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_state', to='hintgen.Hint'),
        ),
    ]
