# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0020_auto_20170117_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcestate',
            old_name='hintmsg',
            new_name='hint',
        ),
    ]
