# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0022_auto_20170117_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Testcase',
        ),
    ]
