# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0025_auto_20170126_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-year', '-semester', 'name']},
        ),
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['level', 'id']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['problem', 'id']},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['problem']},
        ),
    ]
