# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0026_auto_20170126_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hint',
            options={'ordering': ['level', '-id']},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['problem', '-id']},
        ),
    ]
