# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hintgen', '0028_auto_20170126_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonstate',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='anonstate',
            name='next',
        ),
        migrations.RemoveField(
            model_name='canonicalstate',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='canonicalstate',
            name='next',
        ),
        migrations.AddField(
            model_name='state',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder', to='hintgen.State'),
        ),
        migrations.AddField(
            model_name='state',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='hintgen.State'),
        ),
    ]
